### PR TITLE
fix: Refactor apps configuration to explicitly define program path and type

### PR DESCRIPTION
**Pull request by krovuxdev**
Issue solved: the application was not running correctly with `nix run`.

### CODE REVIEW

**Comment by romancitodev** [comment]
Small change, looks fine (I don't use NixOs so I assume that's correct).

I approve this, idk about other core contributors that uses Nix.

**Review by romancitodev — APPROVED** [review]

**Comment by romancitodev** [comment]
@SergioRibera What do you think?

**Review by SergioRibera — APPROVED** [review]
It looks great, I just realized that with the binary change it stopped working command

**Comment by krovuxdev** [comment]
> It looks great, I just realized that with the binary change it stopped working command

Why? It worked fine for me. Could you please check my PR again and try running the command?

**Review by SergioRibera — APPROVED** [review]

**Pull request merged**
